#pragma config(Motor,  port2,           m2,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           m3,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		//flywheel
		if (vexRT[Ch2] > 5) {
			motor[port3] = 50;
			motor[port2] = 50;

			int i = 50;
			while (i < 100) {
				wait1Msec(250);
				motor[port3] -= 5;
				motor[port2] -= 5;
				i += 5;
			}
		} else {
				while (motor[port2] != 0) {
					wait1Msec(20);
					motor[port2] -= 1;
					motor[port3] -= 1;
				}
		}

		//top spin
		if (vexRT[Btn8D]) {
				motor[port4] = 50;
		} else {
				motor[port4] = 0;
		}

		//bot spin
		if (vexRT[Btn8R]) {
				motor[port5] = 50;
		} else {
				motor[port5] = 0;
		}
	}
}
