
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
// Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
bStopTasksBetweenModes = true;

// All activities that occur before the competition starts
// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
// Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
// .....................................................................................
// Insert user code here.
// .....................................................................................

	//auto 4.4.1.B

		// go forward
	motor[port2] = -100;
	motor[port3] = 100;
	wait1Msec(1500);

	//stop
	motor[port2] = 0;
	motor[port3] = 0;
	wait1Msec(600);

	//turn
	motor[port2] = 100;
	motor[port3] = 100;
	wait1Msec(850);

	//stop
	motor[port2] = 0;
	motor[port3] = 0;
	wait1Msec(600);

	//keep going forward
	motor[port2] = -100;
	motor[port3] = 100;
	wait1Msec(2000);

}

/////////////////////////////////////////////////////////////////////////////////////////
//
// User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
// User control code here, inside the loop

	while (true)
		{
	// This is the main execution loop for the user control program. Each time through the loop
	// your program should update motor + servo values based on feedback from the joysticks.

	// .....................................................................................
	// Insert user code here. This is where you use the joystick values to update your motors, etc.
	// .....................................................................................

		int temp = 0;
	int temp1 = 0;
	int x = -1;
	int y = 0;
	int a = 1;
	int b = 0;
	int d = 0;
	int e = 0;

	while (true) {
		if (vexRT[Btn7D] == 1 && y == 0) {
			x+=2;
			y = 1;
		}
		if (x > 1) x = -1;
		if (vexRT[Btn7D] == 0) y = 0;

		if (x > 0) {
			d = vexRT[Ch2];
			e = vexRT[Ch3];
		} else {
			e = vexRT[Ch2];
			d = vexRT[Ch3];
		}

    if (e > 30 || e < -30) motor[port3] = (int) e * -0.8 * x; // RIGHT WHEEL
		else motor[port3] = 0;

		if (d > 30 || d < -30) motor[port2] = (int) d * 0.8 * x; // LEFT WHEEL
		else motor[port2] = 0;

		if (vexRT[Btn8D] == 1 && temp1 == 0) {
			temp++;
			temp1 = 1;
		}
		if (temp == 2) temp = 0;
		if (vexRT[Btn8D] == 0) temp1 = 0;
		if (temp == 1) motor[port4] = 100; //Conveyer belt
		else motor[port4] = 0;

		if (vexRT[Btn6U] == 1 && b == 0) {
			a++;
			b = 1;
		}
		if (a == 2) a = 0;
		if (vexRT[Btn6U] == 0) b = 0;
		if ((a == 0 && SensorValue[dgtl12] == 0) || vexRT[Btn6D] == 1 ) {
			motor[port5] = -100;
			motor[port7] = -100; //Catapult
		}
		else {
			motor[port5] = 0;
			motor[port7] = 0;
		}

		if (vexRT[Btn5U] == 0 && vexRT[Btn5D] == 0) motor[port6] = 0; //pancake flipper
		else if (vexRT[Btn5U] == 1) motor[port6] = 60;
		else if (vexRT[Btn5D] == 1) motor[port6] = -60;
		else motor[port6] = 0;



	}
}

}
