#pragma config(Sensor, dgtl12, ,               sensorTouch)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	while (true) {
    if (vexRT[Ch2] > 30 || vexRT[Ch2] < -30) motor[port3] = vexRT[Ch2] * -0.78; // RIGHT WHEEL
		else motor[port3] = 0;

		if (vexRT[Ch3] > 30 || vexRT[Ch3] < -30) motor[port2] = vexRT[Ch3] * 0.78; // LEFT WHEEL
		else motor[port2] = 0;

		if (vexRT[Btn8D] == 1) motor[port4] = -100;
		else motor[port4] = 0; //Conveyer belt

		if (vexRT[Btn6D] == 1 || SensorValue[dgtl12] == 0) motor[port5] = -100; //Catapult
		else motor[port5] = 0;

  }
}
