#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	int temp = 0;

	while (true) {
    if (vexRT[Ch2] > 20 || vexRT[Ch2] < -20) motor[port3] = vexRT[Ch2] * -1; // RIGHT WHEEL
		else motor[port3] = 0;

		if (vexRT[Ch3] > 20 || vexRT[Ch3] < -20) motor[port2] = vexRT[Ch3]; // LEFT WHEEL
		else motor[port2] = 0;

		if (vexRT[Btn6D] == 1) temp++;
		if (temp == 2) temp = 0;
		if (temp == 1) motor[port4] = -127; //Conveyer belt
		else motor[port4] = 0;

		if (vexRT[Btn5D] == 1 || SensorValue[dgtl1] == 0) motor[port5] = 127; //Catapult
		else motor[port5] = 0;

		if (vexRT[Btn8D] == 1) motor[port9] = -100;
		else motor[port9] = 0;

  }
}
